[quote, GraphQL Blog,https://graphql.org/blog/mocking-with-graphql/]
____
Let’s say your backend is some REST API that is called over HTTP from the browser. You have someone working on the backend, and someone else working on the frontend. The backend code actually determines the shape of the data returned for each REST endpoint, but mocking has to be done in the frontend code.
____

Nothing to do with REST, what you mean is "lazy developers using any paradigm/implementation."

I'd hazard a guess there's more than a few developers out there building GraphQL APIs without mocking them first too.

[quote, GraphQL Blog,https://graphql.org/blog/mocking-with-graphql/]
____
The other reason I often hear for why people don’t mock the backend in their project is because it takes time to set up: first you have to include extra logic in your data fetching layer that lets you turn mocking on and off, and second you have to actually describe what that mock data should look like. For any non-trivial API that requires a lot of tedious work.
____

They're scraping the bottom of the barrel here. Hosting a mock server is a piece of piss, and "switching to it in the client" is the same as anything else. If you've got service discovery then you're all set, but if you want to put an ENV variable in place that's easy too.

[source]
----
if (ENV['MOCK_API']) {
  http_server = 'http://mock.server.api'
}
----